---
title: "Expert Report for the Royal Commission on Antisemitism and Social Cohesion"
author: "Daniel Allington"
date: "2026-04-18"
output:
  word_document: default
  html_document: default
bibliography: "royal-commission.bib"
documentclass: article
csl: "chicago-fullnote-mod.csl"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(knitr)
library(kableExtra)
```

# What is antisemitism?
As the Oxford English Dictionary makes clear, the word 'antisemitism' refers, in its everyday sense, to '[p]rejudice, hostility, or discrimination against Jewish people' [@oed_antisemitism_2025, sense 1]. However, scholars often use the word in a more specific sense, refering not to 'th[e] entire history [of anti-Jewish _praxis_], from its earliest beginnings in classical and pagan times through to the present', but rather to the bigotry and persecution faced by Jews in Europe and its diaspora during a specific historical period which 'beg[an] sometime in the latter part of the nineteenth century' [@seymour_continuity_2019, p. 12]. A discussion of why this is the case may serve to clarify much about the nature of Jew-hate, and also to elucidate key debates over the term itself.

Until the end of the 18th century, Jews were almost universally oppressed on religious grounds. In Europe, full legal rights were available only to Christians, and a range of superstitions arose from the idea that Jews were devil worshippers who bore historic guilt for the killing of Jesus Christ: in particular, they were accused of ritual murder of Christian children [@trachtenberg_devil_1943, p. 124-139], especially in order to consume their blood (the 'blood libel') [@trachtenberg_devil_1943, p. 140-155] or to use their organs in order to treat their own illnesses [@zukier_conspiratorial_1987, p. 101], of poisoning wells used by Christians [@trachtenberg_devil_1943, p. 97-108], of usury (i.e. charging excessive interest on loans) [@trachtenberg_devil_1943, p. 188-194], and of sorcery [@trachtenberg_devil_1943, p. 196-206]. Widely depicted as horned, and sometimes also as tailed, Jews came to be identified directly with the devil [@trachtenberg_devil_1943, p. 193; @bertman_antisemitic_2009; @zukier_conspiratorial_1987, p. 101]. In the Muslim world, Jew-hatred did not have this demonological character, but Jews were permitted to reside only as _dhimmis_: second-class subjects of the ruler, unable to rely on the full protection of the law, yet obliged to pay a special tax and to follow often humiliating restrictions designed to reinforce their contemptible status [@lewis_jews_1987, p. 14; @gilbert_ishmaels_2011, p. 87-88]. 

However, after the Enlightenment, Jews began to achieve emancipation. In 1791, France became the first Christian country to grant full rights to Jews. Over the next hundred years, most European countries followed suit --- except within the Russian Empire, where Jews continued not only to lack rights but also to be persecuted in the most brutal and public fashion --- and, while much of the Muslim world lagged behind in this respect (see in particular the dreadful conditions which prevailed in Persia) [For summary, see @allington_islamist_2025, p. 26-28], modernising rulers of the Ottoman Empire provided legal equality for Jews and abolished the _dhimma_ system in a series of reforms beginning in 1839 and spanning several decades.

It was during this period that the myth of a worldwide Jewish conspiracy was conceived. As Norman Cohn explains in the classic study, that myth 'represents a modern adaptation of th[e] ancient demonological tradition' of Christian anti-Judaism, and holds that

> there exists a secret Jewish government which, though a world-wide network of camouflaged agencies and organisations, controls political parties and governments, the press and public opinion, banks and economic developments. The secret government is supposed to be doing this in pursuance of an age-old plan and with the single aim of achieving Jewish dominion over the entire world; and it is also supposed to be perilously near to achieving this aim. [@cohn_warrant_1967, p. 22-23]

France was, as noted above, the first country to give full rights to Jews, and it was in France that the Jewish conspiracy myth appears first to have germinated, expressed in a forged letter purporting to have been written by a Florentine army officer by the name of J.B. Simonini, and addressed in 1806 to l'Abbé Barruel, the author of a conspiracy theory attributing the French Revolution to the machinations of the Freemasons and the Bavarian Illuminati, to which the fraudulent 'Simonini letter' became a sort of postscriptum [@cohn_warrant_1967, p. 27]. The Jews of what is now Germany were emancipated at different points in the 19th century, depending on where they resided, while indications that Alexander II might emancipate the Jews of the Russian Empire proved false, and it was in the German- and Russian-speaking worlds that the conspiracy myth really took root from the 1860s onwards.

Hermann Goedsche's 1868 German-language novel _Biarritz_, published under the pseudonym of Sir John Retcliffe, included a chapter in which a group of rabbis plot to complete their fiendish takeover of the world [@cohn_warrant_1967, p. 34-36]. From 1972 onwards, this chapter began to be published in Russia as a standalone text, with hints that it was not entirely fictional soon giving way to outright assertions that the words were the record of a secret speech [@cohn_warrant_1967, p. 36-37]. Then, in the early 1870s, Frederick van Millingen, a German-speaking writer from Serbia with a substantial Russian audience, published _World Conquest by the Jews_ in Switzerland under the pseudonym of Osman-Bey, in which he argued that, for the world to experience a Golden Age without war, its people must '[d]rive out the Jews' with an 'enthusiastic shout' of 'Out with the intruders' [Quoted in @cohn_warrant_1967, p. 59].

Although van Millingen was very much a figure of the political right, it was through the works of a German left-wing writer named Wilhelm Marr that the desire to rid the world of Jewish influence came to be incorporated into a full-blown political programme. Marr understood the people of Europe to be divided into three 'races', which he dubbed the 'Slavic', the 'Latin', and the 'Germanic' [@zimmermann_wilhelm_1986, p. 66], and saw Jewish emancipation as a key stage in the 'foreign domination' of Germany by Jews [@musiedlak_wilhelm_2021, p. 83-84]. For Marr, 'race' was more a matter of culture than of biology, and he referred to the characteristic culture of the 'Germanic race' as _Germanenthum_, generally translated as 'Germanism' or 'Germanicness', which --- with its antiquarian implications --- could be placed in opposition to cultural traditions whose origins lay elsewhere in the world [@mees_hitler_2004, p. 258]. Marr thus employed a number of terms in order to emphasise what he saw as the alien nature of German Jews and their (in his view) imported culture. As well as _Judenthum_ or 'Judaism' (which, in German as in English, had the disadvantage of being the name of the Jewish religion), Marr sometimes described Jewish culture as 'Asianism' [@zimmermann_wilhelm_1986, p. 66-68]. However, he came to prefer the term 'Semitic', which brought Jews into his framework of linguistically-named races (as it was the name of the family to which the Jewish language of Hebrew belonged), and provided the derived word 'Semitism' (_Semitismus_), to denote Jewish culture. In his hugely influential 1879 pamphlet, _The Victory of Judaism over Germanism: Viewed from a Nonreligious Point of View_, Marr characterised the Jews as 'a tribe ... which ... was thoroughly hated by all the peoples of the Orient' [@marr_victory_1879_2009, p. 10] and which considered itself to be 'charged with the pleasant task of exterminating all that is not Jewish' [@marr_victory_1879_2009, p. 14]. He argued that, during the reign of the Emperor Titus (who had razed Jerusalem and the Second Temple, but also brought a small number of Jews to Rome), the Jews had turned from military conflict with other Middle Eastern peoples to social corruption of Europeans [@marr_victory_1879_2009, p. 8-9], subsequently finding the Germans to be particular vulnerable to conquest by this means:

> Germanism did not possess sufficient spiritual endurance to protect itself from Judaisation, and so Germany turned step by step into the new promised land for Semites ...

> This tribe, the Jews ... transformed all of its destructive potential into new forms and using these, vanquished the Occident, a victory it could not achieve in the Orient using fire and sword. 

> ...

> ... [O]ur outlook [today] is none other than a time when we Germans will live as slaves under the legal and political feudalism of Judaism. [@marr_victory_1879_2009, p. 14]

Although Marr was far from being the first writer to imagine the hidden hand of an international Jewish conspiracy behind every disagreeable thing in the world, he was the first to transform this paranoid fantasy into a rallying cry for what many of his contemporaries would see as a justified 'war against the Jews' [@zimmermann_wilhelm_1986, p. 78]. Because 'Semitism' was at that point Marr's preferred word for Jewishness, he naturally used the word 'antisemitism' (or, in the original German, _Antisemitismus_) to describe the political programme that he subsequently attempted to lay out.

That programme provided much of the ideological foundation for National Socialism, or Nazism --- although some within that movement, including Hitler himself, prefered to replace 'Germanism' with fantasies of a supposedly prior 'Aryan' culture, hypothetical wellspring not only of everything Germanic, but also of the glories anciently achieved by Persia, Egypt, Greece, and Rome [@mees_hitler_2004, p. 268]. However, it was in Russia that antisemitism first became embedded in government policy, with Jews being scapegoated for widespread political discontentment, and with Alexander III's accession to the throne following his father's assassination being followed by pogroms and a raft of anti-Jewish legislation, and with his son, Nicholas II, taking the view that nine out of ten revolutionaries were Jews [@poliakov_topic_1987, p. 106-7]. It was during this period that Tsarist agents produced the classic antisemitic text now remembered as _The Protocols of the Elders of Zion_: a literary forgery produced by combining a French translation of Goedsche's 1868 chapter with elements adapted from a political satire by Maurice Joly [@cohn_warrant_1967, p. 103-107], and published in various forms from 1903 onwards [@cohn_warrant_1967, p. 65-67].

It is vitally important to understand that, according to the ideology of antisemitism, non-Jews persecuting Jews are striking a blow against an almost cosmic evil whose destruction is necessary for the redemption of the world as a whole. As the historian Norman Cohn explains, 'the organised killers [of the Nazi movement] needed the myth of the Jewish world-conspiracy if they were not to recognise themselves as common thieves and murderers' [@cohn_warrant_1967, p. 268]. For example, an official Nazi Party publication declared in 1937 that 'Jewry's ruthless drive for world domination was stopped only by National Socialism' [Quoted in @bytwerk_believing_2015, p. 214]. Antisemitism thus enables mass-murderers to view themselves as heroes, not lashing out against innocent and often defenceless individuals, but acting in defence of their own civilisation and the wider world --- even if the _individual_ innocence of some of their victims is sometimes acknowledged, as when Hitler conceded that 'many Jews are not aware of the destructive power they represent' [Quoted in @billig_fascists_1978, p. 177-178].

Marr was happy to identify as an antisemite, but many later adherents of his programme preferred to refer to their politics by alternative names. Indeed, the 1944 edition of Theodor Fritsch's _Handbook of the Jewish Question_ --- by that point, a standard Nazi text --- rejected the term 'antisemitism' as 'unsuitable, ... for the reason that there are other peoples with Semitic languages, such as the Arabs, who stand in complete opposition to the Jews' [Quoted in @zimmermann_wilhelm_1986, p. 113-115]. Nonetheless, the name stuck, and, moreover, broadened in meaning, such that it not only continued to denote the specific anti-Jewish politics of Marr and the Nazis, but also became the usual word by which to refer to _any_ form of anti-Jewish action, sentiment, or ideation --- even while the label is resisted by many of those involved.

The above discussion may strike the busy reader as unnecessarily deep in the historical weeds. However, there are two key points which could not have been made otherwise. The first is that it is enduring aspects of the ideological movement which emerged in response to the emancipation of Jewry that give contemporary Jew-hate its characteristic signature. The second is that the question of what to call that movement, and where to draw its boundaries, is far from clear. This is particularly important if sense is to be made of debates over the relationship between antizionism and antisemitism.

# Zionism, antizionism, and antisemitism
The above discussion has focused primarily on Europe. However, it has touched three times upon the Middle East: firstly in its mention of the terrible mistreatment to which Jews were historically subjected in much of the Muslim world, secondly in its inclusion of the Ottoman Empire in the narrative of Jewish emancipation through social progress, and thirdly in its allusion (via quotation) to continuing Arab hostility towards Jews which served as a basis of alliance with the Nazis. All of these things predated the foundation of the State of Israel.

Zionism --- the movement for national self-determination of the Jews in the historic homeland of the Jewish people --- began in the late 19th century, in response to the rise of political antisemitism (itself, as noted above, a backlash against Jewish emancipation). Its most effective spokesperson was Theodor Herzl, who in 1896 published a pamphlet under the title of _The Jewish State_. This work was primarily concerned with the practicalities of founding a state. However, it gave very clear expression to the rationale for doing so, i.e. the recognition that Jews would never be safe so long as long they had to rely on non-Jews for protection:

> No one can deny the gravity of the Jews' situation. Wherever they live in perceptible numbers, they are more or less persecuted. Their equality before the law, granted by statute, has become practically a dead letter. ...

> ... 

> Everything tends, in fact, to one and the same conclusion, which is clearly enunciated in that classic Berlin phrase: 'Juden raus!' (Out with the Jews!)

> I shall now put the Jewish Question in the curtest possible form: Are we to 'get out' now? And if so, to what place?

> Or, may we yet remain? And if so, how long?

> ... Were we as near to the hearts of princes as are their other subjects, even so they could not protect us. They would only feed popular hatred of Jews by showing us too much favour. By 'too much', I really mean less than is claimed as a right by every ordinary citizen, and by every tribe. [@herzl_jewish_1917_1896, 7-8]

Herzl's frame of reference was the situation faced by European Jews. But his proposals struck an immediate chord with the Jews of the Muslim world, whose situation was even worse than that of the Jews of Christendom. Gathering together in a single place offered many benefits for a dispersed and mistreated minority population, and, throughout the 19th century, there had been documented migrations of Middle Eastern Jews to the area around Jerusalem [@gilbert_ishmaels_2011, pp. 119–21]: a city in which they already constituted a majority (albeit a majority kept in an impoverished and vulnerable state by its Muslim rulers) [@gilbert_ishmaels_2011, pp. 106–7]. Indeed, there were Algerian Jews at the First Zionist Congress, and Zionist groups rapidly formed across the Middle East and North Africa [@gilbert_ishmaels_2011, pp. 135–39]. In the early 20th century, many thousands of Middle Eastern Jews escaped persecution and forced conversion by fleeing to the area now known as Israel [@gilbert_ishmaels_2011, p. 131, 147, 157-158].

Until the end of the First World War, that geographical area did not form a unitary territory, being divided between several administrative units. Following the break-up of the Ottoman Empire, it came to be administered by the UK, under a temporary arrangement known as the British Mandate for Palestine. Under British rule, Muhammad Amin al-Husseini --- the hereditary leader of the most powerful Arab clan in the area --- was appointed chief Islamic jurist, or Mufti, for Jerusalem. Seeking to guarantee his own continued authority in the post-Ottoman era, al-Husseini employed both religious and nationalist arguments against coexistence with the Jews, and allied himself both with the Nazis and with the Muslim Brotherhood [See @kuntzel_nazis_2024]. This was the world's first Islamist organisation. It was in many respects modelled on European Nazi and Fascist movements, and paralleled them not only in its ambition to restore the glories of a mythic past [See @allington_islamist_2025, p. 35-36], but also in its hostility to Jews, seeking both to thwart Jewish aspirations towards sovrignty and national self-determination, and to de-emancipate Jewry through the restoration of _dhimma_: the aforementioned discriminatory system under which Jews could only be second-class subjects of Muslim rulers [@allington_islamist_2025, p. 36-37]. 

The extent of the ideological overlap between European antisemites on the one hand and Muslim antisemites on the other should not be underestimated. It is not, for example, that Europeans hated 'Jews' while Islamists and Arab nationalists hated 'Zionists'. The editors of the first edition of the _Protocols of the Elders of Zion_, which appeared just eight years after Herzl's pamphlet, stated that Zionism 'has the task of uniting all the Jews in the whole world in one union --- a union which is more closely knit and more dangerous than the Jesuits' [Quoted in @cohn_warrant_1967, p. 68], while Sergei Nilus introduced his definitive edition as the revelation of a 'strategic plan ... worked out by the leaders of the Jewish people during the many centuries of dispersion, and finally presented to the Council of Elders by "the Prince of the Exiles", Theodor Herzl, at the time of the first Zionist congress, summoned by him at Basel in August 1897' [Quoted in @cohn_warrant_1967, p. 69]. That is, almost from the very moment that Zionism became an organised movement among Jewry, it became incorporated into the conspiracy mythology, with the assumption that world domination was the true purpose of the Zionist movement. However, as well as identifying the international Jewish conspiracy with 'Zionism', European antisemites opposed the real world politics of Zionism too. As Adam Louis-Klein observes, 

> Early texts from the 1920s by Alfred Rosenberg --- later one of the central Nazi propagandists --- framed the 'Zionist menace' as an invasion of Palestine ... . Rosenberg applied classical antisemitic notions of Jewish 'conquest', found in 19th century antisemites such as Wilhelm Marr and Eduard Drumont, equally to Jewish presence in Germany and to Jewish settlement in Palestine. [@louis-klein_antizionism_2026, n.p.]

Thus, the Nazis had much genuine common ground with the Jew-haters of the Middle East, even before they had begun to collaborate with them. As for the latter, they adapted European antisemitic narratives to their own situation. In 1937, while on the run from the British authorities for his leading role in an uprising that killed 80 Jews, al-Husseini issued a pamphlet entitled _Judaism and Islam_, which was subsequently republished by the Nazis. It closely echoed Wilhelm Marr's fantasies of an ancient Jewish war against the European 'races' by accusing Jews of having secretly waged war on Islam for over a thousand years (a theme which would later become central to Nazi propaganda for the region [@herf_nazi_2009, p. 170-171]), and concluded with a call for retaliation and for racial as well as religious exclusivity in the lands then known as Mandatory Palestine:

> To my Muslim brothers of the whole world, I present the history and true experience that Jews cannot deny. The verses from the Quran and the hadiths prove to you that the Jews have been the most bitter foes of Islam and are still trying to destroy it. Do not believe them, they know only hypocrisy and guile.

> Keep together, fight for the Islamic idea, fight for your religion and existence! Do not rest until your land is free from the Jews!

> Do not tolerate the partition plan, for Palestine has been for centuries an Arab country and must remain so. [Translation published in @kuntzel_nazis_2024, p. 136]

Al-Husseini became a key contributor to Nazi propaganda for Muslim audiences, which has been analysed in detail by Jeffrey Herf. Once it was clear that the Axis powers were losing the battle for Africa, this propaganda began to focus on the dire consequences which would follow victory for 'the British, the Jews, and their Allies', and to warn Arabs to prepare for future war against these 'imperialists' [@herf_nazi_2009, p. 172], insisting that 'there is no room on earth for both Arabs and the Jews' [@herf_nazi_2009, p. 173], that '[t]he Jews are preparing death for [Arabs and Muslims] at the hands of the Americans' [@herf_nazi_2009, p. 176], and that 'the world will never be at peace until the Jewish race is exterminated' [@herf_nazi_2009, p. 184]. Nazi broadcasts in Arabic argued that the Jews had started both world wars in order to establish a state in Palestine [@herf_nazi_2009, pp. 189, 198]. Even as the Nazis were engaged in the systematic and industrial extermination of European Jews, Nazi propaganda introduced Arab audiences to the idea that the Zionists intended to 'wipe out' Palestinian Arabs [@herf_nazi_2009, pp. 216–17], thus accusing Jews of the very crime that was being committed against them. In 1944, al-Husseini --- who had for years had full knowledge of the Final Solution --- explicitly called on Arabs to commit genocide against the Jews of the Middle East:

> Arabs! _Rise as one and fight for your sacred rights. Kill the Jews wherever you find them. This pleases God, history and religion. This serves your honour. God is with you._ [Translation published in @herf_nazi_2009, p. 213, emphasis in original]

This war cry was issued shortly before the defeat of the Axis. Like many Nazis and Nazi collaborators, al-Husseini was able escape from justice by fleeing Europe. On the occasion of his return to the Middle East, Hasan al-Banna --- the founder and leader of the Muslim Brotherhood --- gave the following speech:

> The Mufti is Palestine and Palestine is the Mufti. Oh Amin! What a great, stubborn, terrific, wonderful man you are! All these years of exile did not affect your fighting spirit.

> Hitler's and Mussolini's defeat did not frighten you. Your hair did not turn grey of fright and you are still full of life and fight.

> ... Yes, this hero who challenged an empire and fought Zionism, with the help of Hitler and Germany. Germany and Hitler are gone, but Amin al-Husseini will continue the struggle.

> ... The armies of colonisation occupied Germany and hoped to catch Amin, but he was too clever for them. He managed to escape to France and now he returns to his people to resume the struggle against the criminal British and against Zionism. [quoted in @herf_nazi_2009, p. 244]

In these words from the founder of the Islamist movement, there is no distinction to be made between an 'antisemitism' pertaining to Hitler and an 'antizionism' pertaining to al-Husseini. Rather, _both_ leaders are understood to be antizionists and anti-colonialists of the same stripe. There are countless statements from later Islamists which could be used to make the same point. For example, former President Rafsanjani of Iran stated in 2007 that the Nazis were justified in trying to rid Europe of the controlling influence of the 'Zionists' [@spoerl_parallels_2020, p. 222], while Sayyid Qutb --- the founder of Salafi-Jihadism --- wrote as follows in the early 1950s:

> And the Jews did indeed return to evil-doing, so Allah gave to the Muslims power over them. The Muslims then expelled them from the whole of the Arabian Peninsula. ... Then the Jews again returned to evil-doing and consequently Allah sent against them others of his servants, until the modern period. Then Allah brought Hitler to rule over them. And once again today the Jews have returned to evildoing, in the form of 'Israel', which made the Arabs, the owners of the Land, taste of sorrows and woe. So let Allah bring down upon the Jews people who will mete out the worst kind of punishment, as a confirmation of His unequivocal promise [Translation published in @herf_nazi_2009, p. 259]

However, perhaps the clearest indication of unity between the ideological antisemitism of Wilhelm Marr and the antizionism of the Islamists and Arab Nationalists is provided by the founding covenant or charter of Hamas --- the Palestinian branch of the Muslim Brotherhood:

> For a long time, the enemies have been planning, skillfully and with precision, for the achievement of what they have attained. ... With their money, they took control of the world media, news agencies, the press, publishing houses, broadcasting stations, and others. With their money, they stirred revolutions in various parts of the world with the purpose of achieving their interests and reaping the fruit therein. They were behind the French Revolution, the Communist revolution, and most of the revolutions we heard and hear about, here and there. With their money they formed secret societies ... for the purpose of sabotaging societies and achieving Zionist interests. ...

> You may speak as much as you want about regional and world wars. ... There is no war going on anywhere, without having their finger in it. [@hamas_covenant_1988, art. 22]

> Today it is Palestine, tomorrow it will be one country or another. The Zionist plan is limitless. After Palestine, the Zionists aspire to expand from the Nile to the Euphrates. When they will have digested the region they overtook, they will aspire to further expansion, and so on. Their plan is embodied in the _Protocols of the Elders of Zion_, and their present conduct is the best proof of what we are saying. [@hamas_covenant_1988, art. 32]

Although the Soviet Union had fought against Nazi Germany from 1941, when the latter broke the 1939 pact of non-aggression between the two countries, and backed the 1947 United Nations resolution which would have created a Jewish state alongside a Palestinian state [@un_resolution_1947], its leadership had long recognised Arab nationalists as important allies [@shindler_israel_2012, p. 50–64], and officially adopted antizionism as an ideology --- which, in practice, often meant little more than recycling of earlier antisemitic propaganda with references to Jews and a world Jewish conspiracy swapped out for references to Zionists and a world Zionist conspiracy [@byford_conspiracy_2011, p. 63]. As explained above, this was already common practice in Nazi propaganda, and can be traced back to the _Protocols of the Elders of Zion_. Thus, the Soviet Union's flooding of the Middle East with 'antizionist' propaganda can best be viewed as a simple passing of the torch from Nazis to Communists --- with the sole innovation that the Nazis, having become enemies of the Soviet Union, now had to be presented as _allies_, rather than enemies, of the accursed Zionists. This was exactly the line taken in Roman Brodsky's 1974 booklet, _The Truth about Zionism_: a typical piece of Soviet propaganda which both accused Zionists of having worked together with Nazis and repeated the Nazi argument that 'Israel is only a place where world Zionism tries out its strength' and that 'Zionism is capable of spreading its influence everywhere' [Quoted in @billig_anti-jewish_1984ii, p. 30]. As Jovan Byford observes, such arguments became the 'prism' through which the European far left viewed developments in the Middle East [@byford_conspiracy_2011, p. 65].

Similar moves were made on the European far right. For example, Richard Thurlow finds that the British journalist, Douglas Reed --- a supporter of the Strasserite varient of Nazism --- 'ceased referring to Jews' after World War II, and 'switched his attention instead to the emerging State of Israel and the forces of political Zionism' [@thurlow_anti-nazi_1984, p. 30], while Michael Billig argues that the National Front --- from the 1960s until the 1980s, the leading British neo-Nazi organisation --- 'claim[ed] to be opposed to Zionists, not Jews _per se_' in order to present its ideology as 'an ordinary political viewpoint, quite distinct from the emotional hatreds of antisemitism', even while using the word 'Zionism' to refer to the Jewish world conspiracy of antisemitic mythology [@billig_fascists_1978, p. 166]. As Billig found, this position was reflected not only in official publications, but in the thinking of ordinary National Front members, a number of whom he interviewed in great depth:

> Generally, a distinction was claimed between being anti-Zionist and antisemitic. B, having outlined his belief ... in the theory of a Zionist takeover of the world, reacted strongly when asked whether this was antisemitism. He replied firmly:

>> No sir, no sir, I’m most definitely not antisemitic. ... And ... I will say to you that ... the majority of people in the National Front are not antisemitic. I cannot account for every last person, quite obviously, but the mainspring of opinion in the National Front is definitely not antisemitic. Antizionist, yes.

> ...

> Like B, other interviewees were at pains to insist upon a distinction between the concepts of antisemitism and antizionism. According to K, 'we're not antisemitic, we’re antizionist, and there's [a] hell of a difference here'. Similarly, A said, 'Now, we are antizionist, completely antizionist, but please don't misunderstand me when I say that we are not antisemitic, which as you appreciate is a different thing'. ... [A] number of [interviewees] classed the charge [of antisemitism] as a 'smear' and thus to be dismissed as a calculated effort to discredit the National Front. [@billig_fascists_1978, p. 301-302]

Like that in the preceding section, the above discussion may strike the busy reader as deep in the historical weeds. However, it serves a key purpose in demonstrating the impossibility of drawing any sort of line between what are commonly known as antisemitism and antizionism. This impossibility is not simply something that I assert, as author of this report. As the many quotations above clearly indicate, the establishment of a hard distinction between something called 'antisemitism' and something called 'antizionism' would rely on a radical misrepresentation of the historical record.

Some scholars have argued on the basis of evident continuity between Wilhelm Marr's ideology and that of contemporary antizionists that antizionism fundamentally _is_ antisemitism. For example, Alan Johnson observes that the 'demonological Israel' of contemporary antizionism is effectively identical to the 'demonological Jew' of an earlier point in history: 'uniquely malevolent, full of blood lust, all-controlling, the hidden hand, tricksy, always acting in bad faith, the obstacle to a better, purer, more spiritual world, uniquely deserving of punishment, and so on' [@johnson_written_2016, parag. 1.3], while Thorsten Fuchshuber argues that 'antizionism is a new form of Judeophobia only in the sense that what stands between the Jew haters and their enemy (the Jew) has changed', such that 'Israel is merely the new obstacle that stands between Judeophobes and the fulfilment of their unsubstantiated hatred against the Jews' [@fuchshuber_wilhelm_2019, p. 35]. 

By contrast, other scholars argue that this lets certain forms of antizionist discourse off the hook, by focusing attention only on those which most closely resemble the anti-Jewish discourse of past centuries. For example, Adam Louis-Klein argues that '[a]ntizionism is ... not classical antisemitism projected onto Israel, but a distinct ideological and symbolic complex whose core nucleus consists of the coloniser, apartheid, and genocide libels' [@louis-klein_antizionism_2026, n.p.]. While I respect Louis-Klein's argument, I note that this is not a qualitative difference, but a question of emphasis: as this report has shown (at one point through citation of Louis-Klein's own scholarship), accusations of Zionist colonialism and genocide originated with the Nazis, whose ideological predecessor, Wilhelm Marr, had accused Jews of invading Europe, enslaving Germans, and wanting to destroy all non-Jews: clear precursors of all three of Louis-Klein's core antizionist libels. [^genocide] Thus, my own view inclines most closely to that of David Seymour, who argues that 'antizionism subsumes the antisemitism(s) of the past, just as "modern" or "classic" antisemitism contained within it earlier, premodern forms of anti-Judaic praxis' [@seymour_continuity_2019, p. 13]. That is, I take the view that the antizionism of today is not precisely the antisemitism of Wilhelm Marr and his contemporaries, but rather, the antisemitism of Wilhelm Marr and his contemporaries _after having undergone nearly 150 years of ideological evolution_ --- in the course of which, tropes have been re-interpreted, re-prioritised, and added to. For this reason, I consider it reasonable to refer to both as 'antisemitism', and shall do so throughout the remainder of this document, while occasionally using alternatives such as 'Jew-hate'.

[^genocide]: It is worth noting that right wing extremists often accuse 'Zionists' of plotting a genocide of white people --- see e.g. @billig_fascists_1978, p. 182 --- although this is widely recognised as nonsense. Because the accusation of Israeli genocide of Palestinians is, by contrast, widely reported as if proven, it is worth discussing it in slightly more detail. As John Strawson shows, the accusation rests on misrepresentation not only of the facts with regard to Israel's military operations in Gaza, but also of statements made by Israeli leaders. The crime of genocide requires intent to destroy a people, which in the case of Israel is only possible by taking statements out of context and ignoring their obvious referents. @strawson_israel_2026, n.p. 

The historically complex nature of contemporary antisemitism can be seen from a brief consideration of recent crimes in Australia targeting Jews and locations associated with Jews. In 2024, the office of the then Attorney General, Mark Drefus was vandalised, with the words 'Who does AG Mark Dreyfus serve?' being painted on the pavement outside [@buckley_antisemitic_2025]. Although the _occasion_ of this attack was the Israel-Hamas war, it functioned by invoking the longstanding antisemitic trope of Jewish loyalty to supposed international Jewish interests (as seen in Marr's polemics, and also in more influential antisemitic works, such as the _Protocols of the Elders of Zion_). A few months later, the office of Josh Burns --- another Jewish politician --- was attacked by arsonists who spray-painted horns onto a photograph of Burns and added the slogan, 'Zionism is fascism' [@abc_activists_2024]. This act of vandalism combined pseudo-political discourse with European depictions of Jews as demonic, horned figures. Shortly afterwards, the Sydney suburb of Woollahra, known for its large Jewish minority, saw a number of arson attacks combined with anti-Israel graffiti [@buckley_antisemitic_2025, n.p.], while Mount Sinai College --- a Jewish school --- was vandalised not only with the message 'fuck the Jews' but also with the words 'killers' and 'merderers [sic]' [@buckley_antisemitic_2025, n.p.; @willan_heightened_2025, 00:15]: accusations which may have been occasioned by the Israel-Hamas war, but which date back to Medieval Europe.  

These examples (from which I have intentionally left out the massacre which prompted the official inquiry to which this report responds) illustrate two key points. The first is that contemporary Jew-targeting acts are saturated with historical baggage, and as such can only be understood by reference to the whole history of Jew-hate. The second is that, as at earlier stages in history, attacks on individual Jews are often rationalised in terms of the supposed evils of a Jewish or 'Zionist' collective. 

This is, indeed, the only way in which it is possible to understand the statement issued by Iran-backed Islamist group Harakat Ashab al-Yamin al-Islamia on the occasion of the stabbing of two visibly Jewish men in London while this report was in preparation:

> Zionists were targeted by our lone wolves in the Golders Green area of London. The heroic act left two Zionists critically wounded and on the brink of death ...

> Historically, the Jews are the killers of Jesus Christ, and today, the Zionists are the killers of innocent women and children.

> We call upon all free people in the world, especially Muslims, to carry out qualitative operations in defence of humanity, occupied Palestine, al-Aqsa Mosque, and the prisoners. Furthermore, anyone who is able to kill Zionists should not hesitate. [Quoted in @starr_wounded_2026, n.p.]

How is it possible to identify knife attacks against random members of the British public --- apparently singled out not on the basis of their political beliefs (which cannot have been known to the attacker), but, in one case, on the basis of his religious clothing, and, in the other, on the basis of his having emerged from a place of worship --- as 'qualitative operations in defence of humanity'? It is possible because this has been the logic of antisemitism since the term was coined in the late 19th century. As the following section of this report will show, that logic is not shared with other ethnic and religious prejudices.

# Similarities and differences between antisemitism and other prejudices against racial, ethnic, and national groups
While any religious, ethnic, or national group may become the object of prejudice and undeserved hostility, antisemitism is distinctive in that it is founded on an ancient, but constantly evolving body of counter-factual belief concerning the world as a whole. The difference between antisemitism and other forms of group-based hate in this regard may be illustrated by example. 

Here, we may arbitrarily take the example of prejudice and hostility faced by Australians of Samoan origin. Anti-Samoan bigotry is typically founded on a racist assumption that Samoans (and other indigenous Polynesians) are 'violent, unmotivated, and government-dependent' [@radclyffe_fob_2024, p. 1070]. This stereotype is very similar to stereotypes applied to many other immigrant groups, both in Australia and elsewhere in the world. It would be extremely surprising to see anti-Samoan graffiti suggesting that Samoans are enemies of God, or that Samoans in Australia serve secret masters, or that the Samoan government is fascist, or that the Samoan army kills non-Samoan children, or that Samoans and their supporters have an excessive influence on the Australian government --- and perhaps also the governments of other world powers. It would be still more surprising to see attacks on random Samoans justified as 'qualitative operations in defense of humanity'. The idea is bizarre, even verging on the ridiculous. Only Jews are spoken about in this way.

Social psychologists have tended to analyse prejudice in terms of discriminatory behaviour towards the members of a group on the basis of negative stereotypical assumptions about the characteristics of group members [@machery_alleged_2010, p. 229]. These stereotypical assumptions are typically based on a worldview in which the majority community is seen as normal and minority communities are seen as inferior. For example, African Americans have been stereotyped as 'savage, brutish, and dangerous' [@belisle_sociobehavioral_2022, p. 1141], while Australian Aborigines have been stereotyped as 'dirty, drunk, destructive, and unable to live in Western-style housing' [@mellor_contemporary_2003, p. 482], and Afro-Caribbeans living overseas have been stereotyped as 'drug-dealing, gun-toting gang[members]' [@hernandez-ramdwar_challenging_2005, p. 83]. Judgement of individuals on the basis of stereotypical assumptions such as these has the clear potential to motivate discriminatory treatment and even violence. However, ideological Jew-hate cannot be reduced to the making of stereotypical assumptions about personal characteristics, as it consists also in a conspiratorial understanding of world history which frames the targeting of Jews --- and people associated with Jews --- as a legitimate form of political action. This is the unique signature of antisemitism.

# The main drivers of contemporary antisemitism in liberal democracies
It is my view the targeting of Jews in liberal democracies is primarily driven by a one-sided view of Middle Eastern politics, in combination with a tendency to treat individual Jews as proximate representatives of an international Jewish or Zionist collective. Qualitative and quantitative evidence in support of this view verges on the overwhelming.

Recent examples from Australia have already been given, above --- and these are in no way exceptional. In the UK, the Community Security Trust found that 53% of the 3700 antisemitic incidents logged in 2025 'referenced, or were linked to, Israel, Palestine, the Hamas terror attack, or the subsequent war' [@cst_antisemitic_2026, p. 5]. That was the year of the country's first lethal terror attack on a synagogue, carried out by Jihad al-Shamie, who shouted 'this is what they get for killing our children' in an apparent reference to deaths in Gaza [@itv-news_eyewitness_2025, n.p.]. Comparisons may also be drawn with killings elsewhere in the world. Earlier the same year, Elias Rodriguez fatally shot two attendees at a reception at the Capital Jewish Museum in Washington DC, subsequently declaring that he 'did it for Palestine' and 'did it for Gaza' [@bosman_what_2025, n.p.], and, in Colorado, Mohamed Soliman, who used firebombs and a makeshift flamethrower to attack a rally for Israeli hostages while shouting 'Free Palestine!', later stating that he wanted to 'kill all Zionist people' [@sky-news_colorado_2025, n.p.]. High profile terror attacks against elsewhere follow a similar pattern. For example, Mohamed Merah, who in 2012 killed three Jewish children and a rabbi in Toulouse, stated that he did it in revenge for the death of Palestinian children, and Amedy Coulibaly, who in 2015 killed four customers at a kosher supermarket in Paris, informed a local television channel that he had targeted Jews in defence of Muslims in Palestine [@cannon_merah_2024]. (Again, I deliberately make no mention of the Bondi Beach massacre.) In all these cases, explicit statements made by the killers and would-be killers indicate that they struck at Jews and those associated with Jews not because they harboured prejudices against Jews (although that may also have been the case), but because they understood themselves thereby to strike against Israel or Zionism. 

Moreover, while terror attacks are thankfully exceptional events, such a tendency would explain large scale statistical patterns. For example, my own analysis of official police figures for England and Wales shows a 93% rise in the number of hate crimes targeting perceived Jews in the first complete reporting year following the 7 October 2023 Hamas atrocities and the launch of the Israeli military response as compared to the four reporting years which preceded that event [@allington_antisemitic_2026, n.p.]. This would simply make no sense if attacks on Jews were driven by prejudices in the conventional sense of relatively stable negative attitudes towards members of a social group. Indeed, if anything, prejudices against Jews appear --- like criminal acts targeting perceived Jews --- to be driven by political orientations towards Israel: analysing attitudinal data collected from a representative sample of 11394 UK residents between 2020 and 2025, I found proportions of individuals with elevated levels both of 'old' antisemitic attitudes (relating to Jews identified as Jews) and 'new' antisemitic attitudes (relating to Israel and its supporters) to be almost perfectly correlated from one year to the next, with both proportions approximately doubling after 7 October 2023 [@allington_antisemitic_2026, n.p.].

As I found, these increases took place disproportionately among the young. An obvious explanation would be the use of online information sources, which are widely perceived to be saturated with antisemitic propaganda. In the aftermath of the 7 October 2023 attacks, the UK's Counter Terrorism Internet Referral Unit observed what was described as 'an unprecedented 12-fold increase in hateful social media content', with counter terrorism officers raising concerns that 'unsuspecting people' --- especially from younger generations --- were 'becoming "swept up" in sharing "naked antisemitism"', very little of it from the far right [@spring_young_2024, n.p.]. However, it is important not to over-emphasise the role of the online world when much radicalisation appears to take place face-to-face.

As one might expect, there is evidence for a connection between antisemitism and agitation by radicalised members of Muslim communities, much of which is likely to take place in mosques. An ethnographic study of banned Islamist terror group al-Muhajiroun and its leader, Anjem Choudary (currently serving a life sentence for terror offences) found that the Israel-Hamas conflict was regarded as a particularly useful source of propaganda themes:

> Anjem meets regularly with the various local leaders to strategise about which issues to address. As a group, they come up with a list of themes, which the local leaders implement in their respective areas. ... 

> Although the topics range, a large number address 'the oppression' of Muslims. These are the most likely to elicit emotional responses and attract audiences predisposed to sympathise with the general discourse of anger promoted by al-Muhajiroun. In a sample of seventy-eight notices for conferences, debates, demonstrations, seminars, lectures, and rallies between February 1997 and May 2004, 40[%] ... of activities explicitly focused on the 'oppression of Muslims' by non-Muslims. The most common topics were US aggression ... and the Israeli occupation of the Palestinian territories. ... The movement uses language, phrasing, and pictures ... that suggest genocide against Muslims, a technique intended to prompt emotional responses and enhance the prospects that a reader will attend the events. [@wiktorowicz_radical_2005, p. 109]

Such statistical evidence as exists is consistent with the view that Islamists such as Choudary may have been correct in their assessment of the effectiveness of such propaganda as a tool for radicalisation --- although, as always with correlational data, a directly causal relationship cannot be assumed. A 2008 survey of six European nations found that, among 'very religious' Muslims, distrust of Jews ran at more than 70% of those who described themselves as 'fundamentalist', but less than 30% of those who did not [Cited in @jikeli_muslims_2023, p. 21], while my own analysis of survey data collected from British Muslims in 2015 found a clear statistical relationship between antisemitism and various indicators of sympathy for Islamism, with support for Islamic State (for example) running at virtually 0% for the majority of Muslims, but at 10% among Muslims whose antisemitic attitudes were at least 1.4 standard deviations higher than the mean [@allington_islamist_2025, p. 76].

There is no indication today that hate preaching has declined. After 7 October 2023, media reports cited video evidence of imams in British mosques praying for 'Muslims [to] get their victory over the usurping Jews', for the 'purif[ication of] the Al-Aqsa mosque from the filth of the Jews', for 'the victory of the mujahideen fighting Israel', for God to 'destroy' the Jews, 'count them and kill them', and 'make them war booty for the Muslims', and in one case not only calling for 'God [to] rid us of the Jews' but referring to the latter as 'brothers of monkeys and apes' [@rose_brazen_2023, p. 3; @rose_shameless_2023, p. 3]. The representative of a Jewish communal organisation whom I interviewed argued that war between Israel and Hamas is 'used as an excuse to express ... hatred [of Jews] and [Islamist] ideology more openly, and it's also used as a recruiting [tool]' [Interview published in @allington_islamist_2025, p. 51], while a former Islamist to whom I also spoke argued that many imams giving such sermons are simply 'emotionally angry and ... riling up ... the people who are listening to the sermons to be just as emotional', yet warned that 'Islamist groups kind of harness that pain and anger' [@allington_islamist_2025, p. 58]. One extremism expert presented the following analysis of hate preaching:

> [On several] occasions ... the text which has been the subject of the sermon has been a hadith that ... appears in the original founding Hamas Covenant ... which predicts the end times, the final hour [.] ... It's essentially a message which says 'If you kill Jews, God will be pleased with you'. More generally, there have been sermons which offer prayers for the success of the ... the mujahideen who are fighting the Zionist Entity ... . There are also prayers for the destruction of God’s enemies, and of course Jews are always mentioned, but polytheists and ... non-believers are [also] sometimes mentioned. ... And then a third strand of sermons which I have seen on a number of occasions are suggestions that politicians and the media are trying to fool you into thinking that Hamas committed massacres, when Hamas did not commit massacres, and all of this is a lie and it's a pretext for a war and for a genocide that was always being planned and was always going to be executed by Israel, and that the suggestion that people had been murdered by Hamas was invented in order to create a justification for that conflict. [Interview published in @allington_islamist_2025, p. 55]

Although such hate preaching poses a clear danger, there are more mainstream vectors through which a distorted view of the Israel-Hamas conflict is disseminated. Concerningly, mainstream educational institutions not infrequently serve as venues for the transmission of antisemitic messaging, especially in relation to the Israel-Hamas conflict. For example, an internal investigation at University College London not only discovered evidence of 'threats of physical violence and death against both Jewish students and staff', but also raised concerns that, where the targets of such threats raise complaints, 'the complainant[s] will be disadvantaged and / or disbelieved' as a result of the staff culture [@lampert_britains_2025, n.p.]. This was the same university at which a former member of research staff gave an unofficial lecture featuring a string of antisemitic cliches, including the idea that the mainstream media is 'Zionist-controlled', the claim that '"Jews pretty much controlled the financialisation" during the time of Napoleon', and the longstanding myth that Jews once made bread for a religious festival with the blood of a Syrian priest whom they had murdered [@brown_academic_2025, n.p.]. Unsurprisingly, antisemitic attitudes have also become widespread among those who come to such institutions seeking education: a 2025 survey found 29% of UK university students in general, and 38% of students of institutions in the country's elite Russell Group, to consider the 7 October atrocities to be an 'understandable act of resistance' [@standwithus-uk_voice_2025, p. 12], while 51% of Russell Group students were found to take the position that 'those who publicly support Israel on campus should "expect" abuse' [@standwithus-uk_voice_2025, p. 13]. Parallels can be drawn with the entrenchment of extreme anti-Israeli positions within elite US universities, where --- as Cary Nelson observes --- '[m]any faculty who write extensively in opposition to Israel are consumed with hatred', and 'feel empowered to teach fiercely and uniformly antizionist courses' [@nelson_israel_2019, p. 420-421], and too in continental Europe, where multiple universities have severed all ties with Israeli institutions, and where the protections of academic freedom have been declared not to apply to those who question Israel's supposed 'genocide' in Gaza by the rector of Ghent University [@boudry_europe_2026, n.p.]: one of three Belgian universities to award an honorary doctorate to Francesca Albanese [@shapiro_francesca_2026], the UN Special Rapporteur condemned for antisemitism by both Germany and France, as well as by leading Holocaust scholar and (at that time) US Special Envoy to Combat Antisemitism, Deborah Lipstadt [@adl_francesca_2026_2024].

# Appendix: Defining antisemitism for policy purposes
In order to respond to anything on a policy level, it is necessary to be in possession of a clear and explicit definition of what that thing is. The most obvious candidate for an official definition will in most cases be the International Holocaust Remembrance Alliance Working Definition of Antisemitism (henceforth, the IHRA Definition). While I regard this as a reasonably good definition, I would caution the policy community not to expect too much of it. The following discussion should thus not be taken as a critique of the IHRA Definition, but as a realistic appraisal of its limitations.

To begin, the IHRA Definition consists of the following two sentences:

> Antisemitism is a certain perception of Jews, which may be expressed as hatred toward Jews. Rhetorical and physical manifestations of antisemitism are directed toward Jewish or non-Jewish individuals and/or their property, [and] toward Jewish community institutions and religious facilities. [@ihra_definition_2016, p. 1]

The first of these sentences is helpful because of its focus on the cognitive aspects of antisemitism, which essentially consists of a set of beliefs, and does not necessarily manifest as emotional hatred. The second is helpful because it clarifies the typical targets of antisemitism, i.e. institutions --- religious and otherwise --- associated with the Jewish community, as well as both Jewish and non-Jewish individuals and (by extension) their property. However, these sentences are in themselves too vague to be of any use, as the first gives no hint as to the _characteristics_ of the perception of Jews which constitutes antisemitism, and the second gives no hint as to _which_ non-Jewish individuals might find antisemitism directed towards themselves or their property: on the face of it, 'Jewish or non-Jewish individuals' is a category which includes _everyone in the world_. 

It is therefore only in context of the examples following the definition proper that the Definition can have any real meaning or application. This means that any government or other institution adopting the IHRA Definition without making clear that it is adopting the entire document in which the definition is laid out, and not merely the two sentences of the Definition itself, is likely to find that it has failed to adopt anything of any practical significance. 

At this point, it is perhaps encumbent on me to express my professional opinion that every single one of the examples is appropriate and well-chosen. However, the document explicitly states that these examples are only illustrative [@ihra_definition_2016, p. 1]. That is, they do not pretend to provide an exhaustive framework for identifying what is and is not antisemitic in human conduct. As such, they are unlikely to be of much use in resolving arguments as to whether a given act or statement should be regarded as antisemitic: a point that is emphasised by the caveat that the examples '_could_ ... include' certain kinds of speech 'taking into account the overall context' (emphasis added) [@ihra_definition_2016, p. 2]. Together with the explicit statement that the Definition is 'non-legally binding' and indeed only a 'working definition', this caveat clearly signals that the authors of the Definition wished to avoid any appearance of attempting to legislate the boundaries of acceptable speech and conduct.

This is not a flaw of IHRA Definition, whose true purpose is that of a recording instrument. That is, it was not intended to establish certain acts as illegal, but only to support institutions in making decisions as to whether to categorise legal or illegal acts as antisemitic for reporting purposes. Indeed, the document states that '[a]ntisemitic acts are criminal when they are so defined by law' [@ihra_definition_2016, p. 2], which clearly implies that the legality of an act is independent of whether or not it is classifiable, under the Definition, as antisemitic. From this point of view, the key part of the document is perhaps the statement that 'Criminal acts are antisemitic when the targets ... are selected because they are, or are perceived to be, Jewish or linked to Jews' [@ihra_definition_2016, p. 2], and the remainder can potentially be considered to consist largely of guidelines which may help to identify whether the targets of a particular act were indeed selected because of a perception of being Jewish, or Jewish-linked.

In practice, however, the really important part of the document is comprised by the following two sentences:

> Manifestations [of antisemitism] might include the targeting of the state of Israel, conceived as a Jewish collectivity. However, criticism of Israel similar to that levelled against any other country cannot be regarded as antisemitic.  [@ihra_definition_2016, p. 1]



Eleven specific examples, of which seven mention Israel:

> Accusing the Jews as a people, or Israel as a state, of inventing or exaggerating the Holocaust.

> Accusing Jewish citizens of being more loyal to Israel, or to the alleged priorities of Jews worldwide, than to the interests of their own nations.

> Denying the Jewish people their right to self-determination, e.g., by claiming that the existence of a State of Israel is a racist endeavor.

> Applying double standards by requiring of it a behavior not expected or demanded of any other democratic nation.

>  Using the symbols and images associated with classic antisemitism (e.g., claims of Jews killing Jesus or blood libel) to characterize Israel or Israelis.

> Drawing comparisons of contemporary Israeli policy to that of the Nazis.

> Holding Jews collectively responsible for actions of the state of Israel. [@ihra_definition_2016, p. 2]



